### ISSUE TITLE
why operators displaying multiple times in a row in js calculator?

### ISSUE THREAD

**Issue by prinsi-t** [prinsi-t/Js-Calculator#1]
Hello, I’m facing difficulties with my js calculator when I type operators(+, *, /, -) it displays more than one time, I don’t want it to display more than one time.
For example: 2++2, when i press "+" more than one time or any other operators  it should not add another plus sign. 

Can you please help me to solve this problem?

![Screenshot (258)](https://github.com/prinsi-t/Js-Calculator/assets/116324634/fb65433c-7bcc-4317-827b-bcbc5d20b927)

**Comment by LUCASFRANKINC** [comment]
Hello there,

After carefully accessing the functionality, this is what came up:
1. Get the length of the <code>str</code> variable
2. Search for the second last index of the <code>str</code> using this code here: <code>str[str.length - 2]</code>. If it's an operator, get rid of the last character
3. Well said, here is the operator handler function that works as expected:
<code>document.querySelectorAll(".operator").forEach((operator) => {
  operator.addEventListener("click", (event) => {
    str += event.target.innerHTML;
    **const secondLastChar = str[str.length - 2];
    // check if the second last character is an operator
    if (secondLastChar === "+" || secondLastChar === "-" || secondLastChar === "*" || secondLastChar === "/") {
      str = str.slice(0, -2);
      str += event.target.innerHTML;
    }**
    document.querySelector("input").value = str;
  });
});</code>

**Comment by LUCASFRANKINC** [comment]
Uploading prinsi_sltn.mp4…

There's a recording of the solution.
